# Homework Numpy

1. Create a 1D array of numbers from 0 to 9

In [2]:
import numpy as np

In [3]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3×3 NumPy array of all Boolean value Trues

In [9]:
arr_1 = np.random.randn(3, 3)
bool_arr = arr_1 < 0.5    
print(bool_arr)

[[False  True False]
 [ True  True False]
 [False  True  True]]


3.Extract all odd numbers from array of 1-10
4. Replace all odd numbers in an array of 1-10 with the value -1

In [22]:
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr2[arr2%2==1]

array([1, 3, 5, 7, 9])

In [30]:
arr2[arr2%2==1]=-1

In [31]:
arr2

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

5. Convert a 1D array to a 2D array with 2 rows


In [32]:
arr3=np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr3=np.arange(12).reshape(2,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

6. Create two arrays a and b, stack these two arrays vertically use the np.dot and 
np.sum to calculate totals

In [35]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [36]:
b=np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [37]:
np.dot(a,b)

130

In [41]:
np.sum(a)

15

In [42]:
np.sum(b)

40

Extension:
1. Create the following pattern without hardcoding. Use only NumPy functions.

In [49]:
c=np.arange(1,4)

In [50]:
c

array([1, 2, 3])

In [51]:
np.r_[np.repeat(c, 3), np.tile(c, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

2. In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b

In [53]:
d=np.arange(1,6)
e=np.arange(4,10)
d

array([1, 2, 3, 4, 5])

In [54]:
e

array([4, 5, 6, 7, 8, 9])

In [56]:
# From 'a' remove all of 'b'
np.setdiff1d(d,e)

array([1, 2, 3])

In [57]:
np.intersect1d(d,e)

array([4, 5])

In [ ]:
d[2]+e[3]